language: php

php:
  - 7.3
  - 7.4

branches:
  only:
    - master
    - commandRecognize

before_install:
  - cp src/tokenExample.php src/token.php 

install:
  - composer install

script:
  - php vendor/bin/phpunit tests